### PR TITLE
Refactor unit-short parsing

### LINKED ISSUE #3: Result of `#unit("Hz")` is confusing
- `#unit("hz")` ⇒ `h` (hecto ?)
- `#unit("Hz")` ⇒ `zH` (zepto Henry)

Results of `#qty` is similar.

I am using v0.4.2 and I've verified this issue on current main (https://github.com/ChHecker/unify/commit/d2ab4c363246a84e82a6a82e842c397f25716b32).

## Workaround

Don't use units-short: `#unit("hertz")` works as expected.

## Reason

- `h` is a valid prefix (hecto or 100).
- `H` is a valid unit (Henry).
- `z` is a valid prefix (zepto or $10^{-21}$).

Therefore the checks pass, and we try to parse `z` and fail. However, we don't `#panic` and let it go…

## Possible Fix

In `#format-unit-short`, remove the `else if` in the `for` loop…
https://github.com/ChHecker/unify/blob/d2ab4c363246a84e82a6a82e842c397f25716b32/lib.typ#L230-L232
…and add the following immediately after the loop.

```typst
    if acc.len() > 0 {
      panic("invalid unit: " + quantity)
    }
```

This will make `#unit("hz")` into `error: panicked with: "invalid unit: hz"`.

In the same `for` loop, add `and unit == none` in this if, because the prefix must appear before the unit:
https://github.com/ChHecker/unify/blob/d2ab4c363246a84e82a6a82e842c397f25716b32/lib.typ#L223-L225

This will make `#unit("Hz")` into `error: panicked with: "invalid unit: Hz"`.

> [!WARNING]
>
> This does NOT make `#unit("Hz")` ⇒ `Hz`, because `#format-unit-short` is eager — it consumes `H` as Henry first.

## A Bigger Refactor?

I suggest a bigger refactor of the parsing logic in `#format-unit-short`…

1. If `quantity in units-short`, `unit = units-short.at(quantity)`, ✓.
2. If not, divide `quantitiy` into two parts, if the first part is a prefix and the second is a unit, ✓.
3. If not, try to divide at other positions.
4. If all division fail, `panic`.

How do you think so? If you agree but are busy, I can try to work out a PR.

### PR DESCRIPTION
**Pull request by YDX-2147483647**
Resolves #3

💥BREAKING CHANGE: Be eager to match units without prefixes, and require prefixes appear before units.

|                                   |                            Before                            |                    After                    |
| --------------------------------- | :----------------------------------------------------------: | :-----------------------------------------: |
| `#unit("hertz")`                  |                         Hz (Hertz) ✅                         |                    Hz ✅                     |
| `#unit("Hz")`                     |                      zH (zepto-Henry) 😖                      |                    Hz 💥✅                    |
| `#unit("zH")`                     |                      zH (zepto-Henry) ✅                      |                    zH ✅                     |
| `#unit("hz")`                     |                        h (hecto-?) 😖                         | error: panicked with: "invalid unit: hz" 💥✅ |
| `#unit("cm")`                     |                      cm (centi-meter) ✅                      |                    cm ✅                     |
| `#unit("hm")`                     |                      hm (hecto-meter) ✅                      |                    hm ✅                     |
| `#unit("zm")`                     |                      zm (zepto-meter) ✅                      |                    zm ✅                     |
| `#unit("mz")`                     |                        m (micro-?) 😖                         | error: panicked with: "invalid unit: mz" 💥✅ |
| `#unit("Kz")`                     |                     zK (zepto-Kelvin) 😖                      | error: panicked with: "invalid unit: Kz" 💥✅ |
| `#unit("zK")`                     |                     zK (zepto-Kelvin) ✅                      |                    zK ✅                     |
| `#repr(unit("Pa").body.children)` | `(h(…), math-style([P], …), math-style([a], …))` (peta-year) ✅ |  `(h(…), math-style([Pa], …))` (Pascal) 💥✅  |

### CODE REVIEW

**Comment by ChHecker** [comment]
This removes support for multi-letter prefixes. For example, `prefixes.csv` contains `da` (deca), which crashes on your commit.
`#unit("dam")` results in `dam` on the main branch and crashes with your change.

**Comment by YDX-2147483647** [comment]
Sorry I missed that…

---

I discover that both `#unit("dam")` and `#unit("dm")` result in `dam` on the main. In fact, only `d`'s are matched and `a`'s are dropped silently. 



In `prefixes.csv`, both deci ($1/10$) and deca ($10$) are `d`… Is this on purpose?

https://github.com/ChHecker/unify/blob/d2ab4c363246a84e82a6a82e842c397f25716b32/prefixes.csv#L11-L12

**Comment by YDX-2147483647** [comment]
Hi! I've just changed `d` → `da`. If you think that's not the proper way, I can revert it.

**Comment by ChHecker** [comment]
That seems to fix the problem. Thank you for your contribution!

**Pull request merged**
